#!/usr/bin/env python

import os
import shutil

SRC_DIR='/Users/freak/Documents/kicad/eurorack-sequencer-hardware'
SRC_BUILD_DIR='.'
SRC_BUILD='BUILD.md'

DST_DIR='.'
DST_BUILD_DIR='_pages/build'
DST_BUILD_MD='index.md'


FRONTMATTER="""---
title: Build Guide
permalink: /build/
layout: manual
nav: 30
---
"""

src_dir = os.path.join(SRC_DIR, SRC_BUILD_DIR)
dst_dir = os.path.join(DST_DIR, DST_BUILD_DIR)

# copy markdown
src_md = os.path.join(src_dir, SRC_BUILD)
dst_md = os.path.join(dst_dir, DST_BUILD_MD)

markdown = FRONTMATTER + '\n' + open(src_md).read()
open(dst_md, 'w').write(markdown)
