#!/usr/bin/env python

import os
import shutil

SRC_DIR='/Users/freak/Documents/stm32-dev-osx'
SRC_MANUAL_DIR='doc/manual'
SRC_MANUAL_MD='UserManual.md'

DST_DIR='.'
DST_MANUAL_DIR='_pages/manual'
DST_MANUAL_MD='index.md'


FRONTMATTER="""---
title: User Manual
permalink: /manual/
layout: manual
nav: 20
---
"""

src_dir = os.path.join(SRC_DIR, SRC_MANUAL_DIR)
dst_dir = os.path.join(DST_DIR, DST_MANUAL_DIR)

# copy markdown
src_md = os.path.join(src_dir, SRC_MANUAL_MD)
dst_md = os.path.join(dst_dir, DST_MANUAL_MD)

markdown = FRONTMATTER + '\n' + open(src_md).read()
open(dst_md, 'w').write(markdown)

# copy images
src_images = os.path.join(src_dir, 'images')
dst_images = os.path.join(dst_dir, 'images')

shutil.rmtree(dst_images)
shutil.copytree(src_images, dst_images)
