#pragma once

#include "ff/ff.h"

namespace fs {

enum Error {
    OK = FR_OK,
    DISK_ERR = FR_DISK_ERR,
    INT_ERR = FR_INT_ERR,
    NOT_READY = FR_NOT_READY,
    NO_FILE = FR_NO_FILE,
    NO_PATH = FR_NO_PATH,
    INVALID_NAME = FR_INVALID_NAME,
    DENIED = FR_DENIED,
    EXIST = FR_EXIST,
    INVALID_OBJECT = FR_INVALID_OBJECT,
    WRITE_PROTECTED = FR_WRITE_PROTECTED,
    INVALID_DRIVE = FR_INVALID_DRIVE,
    NOT_ENABLED = FR_NOT_ENABLED,
    NO_FILESYSTEM = FR_NO_FILESYSTEM,
    MKFS_ABORTED = FR_MKFS_ABORTED,
    TIMEOUT = FR_TIMEOUT,
    LOCKED = FR_LOCKED,
    NOT_ENOUGH_CORE = FR_NOT_ENOUGH_CORE,
    TOO_MANY_OPEN_FILES = FR_TOO_MANY_OPEN_FILES,
    INVALID_PARAMETER = FR_INVALID_PARAMETER,
    DISK_FULL,
    END_OF_FILE,
    INVALID_CHECKSUM,
};

const char *errorToString(Error error);

} // namespace fs
