#!/bin/sh

BUILD_DIR=build/sim/www/src/apps/sequencer
TESTDRIVE_DIR=_pages/testdrive

# clone gh-pages repository
git clone --branch=gh-pages https://${GH_PAGES_TOKEN}@github.com/westlicht/performer.git gh-pages

# copy simulator files
cp ${BUILD_DIR}/sequencer.* gh-pages/${TESTDRIVE_DIR}

# commit simulator files
cd gh-pages
git config --global user.email "travis@travis-ci.com"
git config --global user.name "Travis CI"
git add ${TESTDRIVE_DIR}/sequencer.*
git commit --message "Travis simulator build: $TRAVIS_BUILD_NUMBER"
git push
cd ..

# remove gh-pages repository
rm -rf gh-pages
