#!/bin/sh

BUILD_DIR=build/sim/www/src/apps/sequencer
SIMULATOR_DIR=_pages/testdrive

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}

commit_simulator_files() {
  git checkout -b gh-pages
  mkdir -p ${SIMULATOR_DIR}
  cp ${BUILD_DIR}/sequencer.* ${SIMULATOR_DIR}
  git add ${SIMULATOR_DIR}/sequencer.*
  git commit --message "Travis simulator build: $TRAVIS_BUILD_NUMBER"
}

upload_files() {
  git remote add origin-pages https://${GH_TOKEN}@github.com/westlicht/performer.git > /dev/null 2>&1
  git push --quiet --set-upstream origin-pages gh-pages
}

setup_git
commit_simulator_files
upload_files
