#!/usr/bin/env python

import sys
import hashlib
import binascii

if len(sys.argv) != 3:
    print('usage: makeupdate [infile] [outfile]')
    sys.exit(1)

infile = sys.argv[1]
outfile = sys.argv[2]

print('makeupdate ' + infile + ' -> ' + outfile)

data = open(infile, 'rb').read()
m = hashlib.md5(data)
md5sum = m.digest()
open(outfile, 'wb').write(data + md5sum)

print('size: ' + str(len(data)) + ' bytes')
print('md5sum: ' + binascii.hexlify(md5sum).decode('utf-8'))
