name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  stm32:
    name: Hardware Platform (STM32)
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: setup
      run: make setup_stm32
    - name: build
      run: (cd build/stm32/release && make -j)
    - name: deploy
      run: make deploy
  sim_linux:
    name: Simulator Platform (Linux)
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: dependencies
      run: sudo apt install -y libsdl2-dev libasound2-dev mesa-common-dev python3.7 python3.7-dev
    - name: setup
      run: make setup_sim
    - name: build
      run: (cd build/sim/release && make -j)
    - name: test
      run: (cd build/sim/release && make test)
  sim_macos:
    name: Simulator Platform (Linux)
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: dependencies
      run: brew install sdl2
    - name: setup
      run: make setup_sim
    - name: build
      run: (cd build/sim/release && make -j)
    - name: test
      run: (cd build/sim/release && make test)
