name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  stm32:
    name: Hardware Platform (STM32)
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: make setup_stm32
    - name: build
      run: (cd build/stm32/release && make -j)
    - name: deploy
      run: make deploy
